### ISSUE TITLE
Setting to list room in directory (or not) is ignored

### ISSUE THREAD

**Issue by thrrgilag** [33mhz/pnut-patter#18]
My public test rooms are shown in the directory even though the option is not set.  For example channel 178 - monkeystew test

**Comment by 33mhz** [comment]
Ah... yes... The ancient patter of yore actually manually indexed rooms, with a dedicated user account and channels for indexing. It was built before App.net's channel search was an option. I'll think about what to change that option to...

**Comment by 33mhz** [comment]
Pnut has significantly better search functionality, so I think I won't reinstate a manual index. Leaving the option off, and will reimplement the actual text search. The options were removed.
